# Site settings
title: Blog de Solar Reflex
email: solar_reflex@hotmail.com
author: José Manuel Alberca
description: > # this means to ignore newlines until "baseurl:"
  Blog sobre la instalación de láminas solares y problemas relativos al cristal.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.solarreflex.es" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
host: 0.0.0.0
github:
  repo: solarreflex/solarreflex.github.io
  branch: master
